### PR TITLE
Handle ui errors using domain validations

### LINKED ISSUE #8: How to handle UI validation?
One of the common use cases in UI applications is to validate UI data such as forms. Usually, this validation comes from business rules ("password cannot be shorter than 8 chars", "email must be from a valid provider").

As we know, business rules should live in the "business side" of our app: The domain/application layers.

Questions:

* What's the best way to handle these validations when used along with tools such as [vuelidate](https://vuelidate.js.org/), [veevalidate](https://logaretm.github.io/vee-validate/)…?
* Do we need these tools?
* How can we express these validations (for example, using Value Objects)?
* Can we leverage the `Result` class here, too, to make everything more expressive and flexible?

I'd say a sensible flow would be:

`user types a value / blurs from an input` -> `validator tool triggers a use case (something like createPassword?` -> `if use case succeeds, everything's ok. if use case fails, display error message`.

However, I'm not sure how verbose/complex this might become, defeating its purpose.

### PR DESCRIPTION
**Pull request by edufarre**
Closes #8 

This PR is a proof of concept about how we could handle the UI errors using/storing our object value' validations into the `@models/**/domain` folder. Thus having the business logic where it should be instead of different `validations` folders across the project.

⚠️ As you can see, we switched between validation libraries, we are currently using VeeValidate instead of Vuelidate because the one we have been using have some caveats and it does not fit our need anymore.

### CODE REVIEW

File: src/shared/result/Result.ts [hunk 1]
```diff
@@ -1,3 +1,4 @@
+/* eslint-disable @typescript-eslint/no-non-null-assertion */
```
Comment (afontcu) [inline src/shared/result/Result.ts:1]: guess this is a leftover?

```suggestion
```

File: src/ui/plugins/veeValidate.ts [hunk 2]
```diff
@@ -0,0 +1,16 @@
...
+import { createPassword } from '@modules/password/domain'
+import { ParseError } from '@shared/ParseError'
+
+extend('password', (value: string) => {
+  const result = createPassword(value)
+  if (result.isOk()) {
+    return true
+  }
+
+  return JSON.stringify(result.error.map((e: ParseError) => e.message))
```
Comment (afontcu) [inline src/ui/plugins/veeValidate.ts:12]: My guess is that types here and potentially redundant, so we might be able to skip the import statement, too:

```js
return JSON.stringify(result.error.map((e) => e.message))
```

File: src/shared/collectErrors/CollectErrors.ts [hunk 3]
```diff
@@ -0,0 +1,15 @@
+import { ParseError } from '@shared/ParseError'
+
+type Validator<T> = (val: T) => ParseError | null
+
+export const collectErrors = <T>(
```
Comment (afontcu) [inline src/shared/collectErrors/CollectErrors.ts:5]: Since this is collecting parsing errors, maybe we could be more explicit

```suggestion
export const collectParseErrors = <T>(
```

File: src/modules/password/domain/password.mock.ts [hunk 4]
```diff
@@ -0,0 +1,3 @@
+import { createPassword } from './password.types'
+
+export const mockPassword = createPassword('12345678')
```
Comment (afontcu) [inline src/modules/password/domain/password.mock.ts:3]: we could use this in the tests 😬

Comment (edufarre) [reply src/modules/password/domain/password.mock.ts:3]: What about the one that checks if `respondWithParseErrors` is called?

File: src/shared/Nominal.ts [hunk 5]
```diff
@@ -0,0 +1,7 @@
+/**
+ * Create an opaque type, which hides its internal details from the public, and can only be created
+ * by being used explicitly. The generic type parameter can be anything. It doesn't have to be an object.
+ */
```
Comment (afontcu) [inline src/shared/Nominal.ts:4]: In a future PR we could add some examples here


```ts
const something = 'whatever' as Nominal<string, 'something'>
const something2 = 'something2' as Nominal<string, 'something'>
const somethingDiff = 'whatever' as Nominal<string, 'somethingDiff'>

assert(something === something2) // true
assert(something === somethingDiff) // false
```

File: src/ui/plugins/veeValidate.ts [hunk 6]
```diff
@@ -0,0 +1,31 @@
...
+})
+
+extend('required', {
+  ...required,
+  message: 'required',
+})
+
+extend('confirmed', {
+  params: ['target'],
+  validate(baseValue, { target }) {
```
Comment (afontcu) [inline src/ui/plugins/veeValidate.ts:23]: looks like I'm getting a type error on `npm run dev` here 🤔 

```
 ERROR  ERROR in src/ui/plugins/veeValidate.ts:23:25                                     
TS2339: Property 'target' does not exist on type 'any[] | Record<string, any>'.
    21 | extend('confirmed', {
    22 |   params: ['target'],
  > 23 |   validate(baseValue, { target }) {
       |                         ^^^^^^
    24 |     return baseValue === target
    25 |   },
    26 |   message: 'confirmed',
```

File: src/ui/plugins/veeValidate.ts [hunk 7]
```diff
@@ -0,0 +1,31 @@
...
+
+import { createPassword } from '@modules/password/domain'
+
+extend('password', (value: string) => {
+  const result = createPassword(value)
+  if (result.isOk()) {
+    return true
+  }
+
+  return JSON.stringify(result.error.map((e) => e.message))
```
Comment (afontcu) [inline src/ui/plugins/veeValidate.ts:13]: In a future PR we might want to uncover better ways of passing these errors between validators and UI. 


Question, btw: did we find a way to "merge" array-like and string-link validations?

File: src/modules/password/domain/password.mock.ts (hunk 4 above)
Comment (afontcu) [reply src/modules/password/domain/password.mock.ts:3]: hummmmm `export const mockInvalidPassword = createPassword('12')` maybe? We should def explore the object mother pattern, or other patterns to provide sensible values to our tests 👍

**Review by anxodio — APPROVED** [review]
LGTM. I will wait until thursday to see if another front-end wants to review it, but if not, IMHO you pairing work is a way to review it and approve it too. :)

File: src/ui/plugins/veeValidate.ts [hunk 8]
```diff
@@ -0,0 +1,27 @@
...
+
+import { createPassword } from '@modules/password/domain'
+
+extend('password', (value: string) => {
+  const result = createPassword(value)
+  if (result.isOk()) {
+    return true
+  }
+
+  console.log('this --> ', this)
```
Comment (afontcu) [inline src/ui/plugins/veeValidate.ts:13]:
```suggestion
```

Comment (edufarre) [reply src/ui/plugins/veeValidate.ts:13]: My bad

**Review by afontcu — APPROVED** [review]
